import apiClient from "../apiClient";

export const autoGenerateDiary = async (tags: string[]) => {
  const res = await apiClient.post("/utils/auto-generate", { tags });
  return res.data?.content;
};
